name: PyInstaller Build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: PyInstaller Build
        run: |
          pyinstaller -F main.py -n mullvad-ping-py
      - name: Rename Binaries
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              mv dist/mullvad-ping-py dist/mullvad-ping-py-linux
          elif [ "$RUNNER_OS" == "Windows" ]; then
              mv dist/mullvad-ping-py.exe dist/mullvad-ping-py-windows.exe
          elif [ "$RUNNER_OS" == "macOS" ]; then
              mv dist/mullvad-ping-py dist/mullvad-ping-py-macos
          fi
        shell: bash
      - uses: benjlevesque/short-sha@v2.1
        id: short-sha
        with:
          length: 6
      - uses: actions/upload-artifact@v3
        name: Upload Artifact
        with:
          name: mullvad-ping-py-${{ env.SHA }}
          path: dist/